name: Python app for github test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.19
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.19
    - name: Install dependecies
      working-directory: scaffold
      run: |
        make install-azure
    - name: Lint with Pylint
      working-directory: scaffold
      run: |
        make lint
    - name: Test with Pytest
      working-directory: scaffold
      run: |
        make test
    - name: Format code with Python black
      working-directory: scaffold
      run: |
        make format
